ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ARG PUID=1000
ARG PGID=1000
#
RUN set -xe \
    && apk add --no-cache --purge -uU sudo curl ca-certificates openssh-client \
    && apk --update add --virtual .build-dependencies python-dev libffi-dev openssl-dev build-base \
    && pip install --no-cache --upgrade ansible \
    && apk del --purge .build-dependencies \
    && mkdir -p /etc/ansible \
    && echo 'localhost' > /etc/ansible/hosts \
    && rm -rf /var/cache/apk/* /tmp/*
# ENTRYPOINT ["/init"]
# ENTRYPOINT ["/usr/bin/python"]
# ENTRYPOINT ["ansible"]
# ENTRYPOINT ["ansible-playbook"]
